Dynamically generate signed URL for file server objects
deepfence/ThreatMapper pull request #2074
Opened 2024-04-09 12:18 UTC by ramanan-ravi

https://github.com/deepfence/enterprise-roadmap/issues/2172

2024-04-10 04:09 UTC, noboruma commented
We need to cache those pre-signed URL in `redis` so that `deepfence_server` don't spend too much time generating those. My worry is it might be putting extra burden on the file server to generate that many continuously, especially since we request those URLs every 30s per agent, so this won't scale.

With that being said, I am not sure pre-signed URL are a good idea now. Since all our agents are authenticated, there is no need to do all that extra work, we could:
- Rely on JWT instead
- By using JWT, we can adapt the URL and change the domain at the agent level directly, so we don't need to touch URL at all

2024-04-10 10:34 UTC, gnmahanth approved these changes

2024-04-11 00:04 UTC, noboruma approved these changes

2024-04-11 00:07 UTC, noboruma commented on deepfence_utils/threatintel/common.go
> +		ttlCache.Set(consoleURL+fName, exposedURL, threatintelPollDuration)
This operation is not thread safe - we might have multiple requests accessing the same thing

2024-04-11 00:09 UTC, noboruma requested changes
Removing previous approval after checking thread safety

2024-04-11 05:05 UTC, noboruma commented on deepfence_utils/threatintel/common.go
> +		ttlCache.Set(consoleURL+fName, exposedURL, threatintelPollDuration)
Actually I confused `set` operation that is not safe with `Set` operation that is safe:
https://github.com/jellydator/ttlcache/blob/v3/cache.go#L313

2024-04-11 05:06 UTC, noboruma approved these changes

2024-04-11 11:02 UTC, merged