update kubernetes console install instructions
deepfence/ThreatMapper pull request #2160
Opened 2024-05-24 12:52 UTC by gnmahanth

2024-05-24 13:49 UTC, ramanan-ravi requested changes

2024-05-24 13:49 UTC, ramanan-ravi commented on docs/docs/console/kubernetes.md
> +    To create a ingress service refer section `Deploy Router Helm Chart With Ingress Enabled`
```
To create a ingress service refer section [Deploy Router Helm Chart With Ingress Enabled](#deploy-router-helm-chart-with-ingress-enabled)
```

2024-05-24 13:55 UTC, ramanan-ravi commented on docs/docs/console/kubernetes.md
> +# Prerequisites
```
## Prerequisites
```

This change is required for this
![image](https://github.com/deepfence/ThreatMapper/assets/38394463/6bc73762-a4d3-492b-9005-16f225ac4add)

2024-05-24 13:58 UTC, ramanan-ravi approved these changes

2024-05-27 08:19 UTC, akumars1 approved these changes

2024-05-27 08:20 UTC, merged