Adds the filters/tab for the different view on topology page
deepfence/ThreatMapper pull request #267
Opened 2022-02-10 10:53 UTC by pandyamarut

Signed-off-by: Marut Pandya <pandyamarut@gmail.com>

Changes proposed in this pull request:
- Adds the different view on topology graph view and table view as well.
- Edge color is changed on graph view.

@deepfence/engineering

2022-02-10 10:57 UTC, pandyamarut commented
<img width="1792" alt="Screenshot 2022-02-10 at 4 23 59 PM" src="https://user-images.githubusercontent.com/28846178/153392689-57a4b3dc-5ec7-43e2-82e1-92d80d64b749.png">
<img width="1707" alt="Screenshot 2022-02-10 at 4 24 38 PM" src="https://user-images.githubusercontent.com/28846178/153393003-dc22c8b0-166c-49d3-b876-c42d61e55153.png">



Screenshots for ref.

2022-02-18 08:56 UTC, manV requested changes
Other observations
1. See if we can fix `onLayoutEnd failed RangeError: Maximum call stack size exceeded` in case of one node in the graph.
2. process and container sorting in hosts table
3. table shimmer loading while changing views does not seem to work
4. when a filter is applied in hosts view, if I switch to any other view and back, filter is still applied but the dropdown does not show that.
5. if I select any rows in table view and swich to another table view, action button stays active.

2022-02-21 04:23 UTC, pandyamarut commented on deepfence_ui/app/scripts/components/multi-cloud-table/multi-cloud-table.js
> +const themeCb = theme => ({
existing dropdown can be used in different use case. 
on topology we have used this one only in filters etc.

2022-02-28 05:11 UTC, manV approved these changes

2022-03-02 07:14 UTC, merged